### ISSUE TITLE
CocoaPods集成在iOS 13.5.1真机上闪退

### ISSUE THREAD

**Issue by muyexi** [GeeTeam/gt3-ios-cocoapods-support#1]
如题，在模拟器上没问题

> -[GT3CaptchaManager allKeys]: unrecognized selector sent to instance

**Comment by roti13island** [comment]
在怎样的场景下触发的？是必现吗 我们也遇到 unrecognized selector 的问题 但不是必现的

**Comment by NikoXu** [comment]
为提供明确的崩溃信息
