### ISSUE TITLE
Support Apple M1 Chip

### ISSUE THREAD

**Issue by dragnea** [GeeTeam/gt3-ios-cocoapods-support#5]
Compiling on mac with Apple M1 is impossible without using Rosetta, Xcode performance being drastically reduced.

Here's the error:
ld: in /.../GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha(GT3Captcha_vers.o), building for iOS Simulator, but linking in object file built for iOS, file '/.../GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha' for architecture arm64

SDK version: 0.14.11
Xcode 13.1 / iOS 15
Apple MacBook Pro M1 2021

**Comment by NikoXu** [comment]
> Compiling on mac with Apple M1 is impossible without using Rosetta, Xcode performance being drastically reduced.
> 
> Here's the error: ld: in /.../GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha(GT3Captcha_vers.o), building for iOS Simulator, but linking in object file built for iOS, file '/.../GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha' for architecture arm64
> 
> SDK version: 0.14.11 Xcode 13.1 / iOS 15 Apple MacBook Pro M1 2021

Sorry about that. Currently we have to exclude arm64 for the simulator architecture.
We will provide XCFramework to support it in the future.

**Comment by laveneam** [comment]
I encounter the same issue. 
Any updates on that?

**Comment by NikoXu** [comment]
> I encounter the same issue. Any updates on that?

Here's good news and bad news.

**Good one:**
We plan to release XCFramework next week.

**Bad one:**
Considering CocoaPods compatibility, we will only provide directly download of XCFramework.

**Comment by NikoXu** [comment]
@dragnea @laveneam 
We can download GT3Captcha.xcframework manually from here: 
https://docs.geetest.com/captcha/deploy/client/ios#Installation

**Comment by dragnea** [comment]
@NikoXu awesome! Can't wait to test it.
Thank you!
