### ISSUE TITLE
Support xcode 15 please

### ISSUE THREAD

**Issue by Decembrist** [GeeTeam/gt3-ios-cocoapods-support#8]
Greetings
On the new xcode 15 it gives an error

building for 'iOS-simulator', but linking in object file (/***/Pods/GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha[arm64][2](GT3Captcha_vers.o)) built for 'iOS'

**Comment by sunnyGeetest** [comment]
@Decembrist 
Please use the pod repository `https://github.com/GeeTeam/gt3-xcframework-support.git`
